version: "3"

services: 
  client:
    build: client/
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  server:
    build: server/
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
  